stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - Diagnosis_flowchart/
      - Finished/
    outs:
      - data/raw:
          cache: true

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - data/raw/
    outs:
      - data/interim:
          cache: true

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - data/interim/
    outs:
      - data/processed:
          cache: true

  model_building:
    cmd: python src/model_building.py
    deps:
      - data/processed/
    outs:
      - models/faiss_index:
          cache: true

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - models/faiss_index/
    outs:
      - reports/metrics.json:
          cache: false
      - dvclive/:
          cache: false

  app:
    cmd: streamlit run src/app.py
    deps:
      - src/app.py
      - models/faiss_index/
      - data/processed/