data_ingestion:
  max_files: 5

text_splitter:
  chunk_size: 400
  chunk_overlap: 50

embedding:
  model_name: distilbert-base-uncased
  device: cpu
  normalize_embeddings: true

retrieval:
  top_k: 4

llm:
  model_name: llama-3.3-70b-versatile
  temperature: 0.0